spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://member-service:8081
          predicates:
            - Path=/members/**
          filters:
            - AuthenticationHeaderFilter
        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationHeaderFilter
        - id: housing-service
          uri: http://housing-service:8083
          predicates:
            - Path=/housings/**
          filters:
            - AuthenticationHeaderFilter
        - id: subscription-service
          uri: http://subscription-service:8084
          predicates:
            - Path=/subscriptions/**
          filters:
            - AuthenticationHeaderFilter
        - id: community-service
          uri: http://community-service:8085
          predicates:
            - Path=/community/**
          filters:
            - AuthenticationHeaderFilter
        - id: notification-service
          uri: http://notification-service:8086
          predicates:
            - Path=/notifications/**
          filters:
            - AuthenticationHeaderFilter