#lh-api:
#  base-url: https://apis.data.go.kr/B552555/lhNoticeInfo1/getNoticeInfo1
#  service-key: lQSP9FvGRXU/HHFK8bmllNrhzwyu+gM3tQuEBavnNP2XdaSRen6s9CKfj7IgYSgdIQnipKn69HgYsAe0u3QmgQ==

server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

